name: 'Jake for GitHub Actions'
author: 'Sonatype'
description: 'Run Sonatype Jake as part of your GitHub Actions workflow.'
inputs:
  packagesListFile:
    description: 'The path to a file containing the list of packages, typically the output from a "conda list" command.'
    required: false
    default: packages.list
  jakeCommand:
    description: 'Optional jake command. Defaults to "ddt"'
    required: false
    default: 'ddt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.packagesListFile }}
    - ${{ inputs.jakeCommand }}
branding:
  icon: 'shield'
  color: 'gray-dark'
